FROM node:18

WORKDIR /app

# Copia e instala dependências
COPY package*.json ./
RUN npm install

# Copia o restante dos arquivos
COPY . .

# Apenas gera o cliente (sem conectar ao banco)
RUN npx prisma generate

# Expõe a porta
EXPOSE 3000

# O comando será executado pelo docker-compose
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]